name: dawo
description: Beginner Dart programmers kickoff to develop a glorious package.
version: 0.0.3
author: Heikki K Lappalainen <heikkiklappalainen@gmail.com.com>
homepage: https://dawopack.blogspot.fi/


environment:
  sdk: '>=1.20.1 <2.0.0'

web:
  compiler:
    debug: dartdevc

dependencies:
  browser: "^0.10.0+2"

dev_dependencies:
  test: "^0.12.24+2"
