name: dawo
description: Beginner Dart programmers project to learn dartlang by developing a package.
version: 0.0.7
author: Heikki K Lappalainen <heikkiklappalainen@gmail.com.com>
homepage: https://github.com/heiklap/dawo


environment:
  sdk: '>=1.23.0-dev.11.5 <2.0.0'

web:
  compiler:
    debug: dartdevc

dependencies:
  http: ^0.11.3+16
  http_server: ^0.9.6
  io: "^0.3.0"
  intl: "^0.15.2"
  browser: "^0.10.0+2"
  dawolang: ^0.0.1

dev_dependencies:
  test: "^0.12.24+2"
