name: dawo
description: Beginner Dart programmers project to learn dartlang by developing a package.
version: 0.0.78
author: Heikki K Lappalainen <heikkiklappalainen@gmail.com.com>
homepage: https://github.com/heiklap/dawo

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  # http: ^0.12.0
  # http_server: ^0.9.6
  intl: "^0.15.2"
  dawolang: ^0.0.2

dev_dependencies:
  build_runner: any
  build_web_compilers: any
