name: dawo
description: Project to learn basics of dartlang, ecosystem and packages.
version: 0.2.0

homepage: https://github.com/heiklap/dawo

environment:
  # sdk: '>=2.1.7 <3.0.0'
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  # http: ^0.12.0
  # http_server: ^0.9.6
  intl: ^0.17.0
  dawolang: ^0.1.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
