name: dawo
description: Beginner Dart programmers kickoff to develop a glorious package.
version: 0.0.5
author: Heikki K Lappalainen <heikkiklappalainen@gmail.com.com>
homepage: https://github.com/heiklap/dawo


environment:
  sdk: '2.0.0-dev.7.0'

web:
  compiler:
    debug: dartdevc

dependencies:
  browser: "^0.10.0+2"
  dawolang:
    path: C:\Users\Public\IdeaDart\dawolang

dev_dependencies:
  test: "^0.12.24+2"
