name: dawo
description: Beginner Dart programmers project to learn dartlang by developing a package.
version: 0.0.75
author: Heikki K Lappalainen <heikkiklappalainen@gmail.com.com>
homepage: https://github.com/heiklap/dawo


environment:
  sdk: '<=2.0.0-dev.68.0 <2.0.0'
  #sdk: '2.0.0-dev.63.0'
#TODO  is  "dartdevc" needed when build_runner??
#web:
#  compiler:
#    debug: dartdevc

dependencies:
  http: ^0.11.3+16
  http_server: ^0.9.6
  io: "^0.3.0"
  intl: "^0.15.2"
  browser: "^0.10.0+2"
  dawolang: "^0.0.1"

dev_dependencies:
  test: "^0.12.24+2"
  build_runner: any
  build_test: any
  build_web_compilers: any
